### ISSUE TITLE
Req. Slt s12

### ISSUE THREAD

**Issue by pradeep5055** [speedforce-lk/dialog-broadband-zlt-s12-pro-stock-unlocked-firmware#1]
S12 Slt ekath dendoo

**Comment by speedforce-lk** [comment]
Router එකෙක් දෙනවා නම් dump කරලා දාන්න පුළුවන්. මට SLT S12 Pro එකක් අරගන්න සල්ලි නැ.

**Comment by pradeep5055** [comment]
Hari contact no ekak thiyenawada

**Comment by pradeep5055** [comment]
anydesk walin karana puluwanda

**Comment by speedforce-lk** [comment]
Dump කරන විදිය කියල දෙන්නම් , AnyDesk නම් කරන්න බැරි වෙයි. 

https://t.me/speedforce_LK

**Comment by AchiYh** [comment]
need help pls give me your contact number.. or any other contact method
